### ISSUE TITLE
K-8 Scope and Sequence

### ISSUE THREAD

**Issue by joshrtay** [9dots/master-coding-todo#1]

**Comment by joshrtay** [comment]
- coding concepts/principles
- computational thinking principles
- coding languages
- software design principles (commenting, reusability, modularity, testability)
- software design process (pseudocode, write code, review)
- project design process (planning, executing, analyzing)
- digital citizenship skills
- how to use a computer

scope & sequence components: https://docs.google.com/document/d/135PfTfWRVEeS3CQMT4VGWwtTsc8L1an_DIrOediSJK4/edit?ts=577fecd4

**Comment by deliema** [comment]
https://csta.acm.org/Curriculum/sub/K12Standards.html

**Comment by deliema** [comment]
Plan for deploying scope & sequence
- give teachers the scope & sequence and allow them to branch off
