### ISSUE TITLE
Values and Goals

### ISSUE THREAD

**Issue by joshrtay** [9dots/master-coding-todo#2]

**Comment by joshrtay** [comment]
Encompassing all coding projects at 9 Dots:
- students
- teachers
- parents
- admin

**Comment by deliema** [comment]
Sources of values and goals:
- Common Core/CSTA (standards docs)
- Teachers' classroom experiences
- Informal teachers' classroom experiences
- Research (validated practices and new goals)
- Workforce needs

**Comment by deliema** [comment]
- Outcome goals
- Process goals
