### ISSUE TITLE
coding research

### ISSUE THREAD

**Issue by joshrtay** [9dots/master-coding-todo#9]
- survey of existing intro to CS courses for all age levels:
  - concepts
  - style guides
  - structure of the course
  - structure of lessons
  - assignments
- survey of coding research:
  - teaching
  - learning
  - tools
  - constructs

**Comment by joshrtay** [comment]
- survey of existing tools
  - directed tools
  - sandbox tools
  - robotics tools
  - communication tools
  - board games
  - fiction books

**Comment by deliema** [comment]
- http://www.corestandards.org/Math/Practice/
- http://www.nextgenscience.org/topic-arrangement/msengineering-design
- http://www.nextgenscience.org/sites/default/files/Appendix%20F%20%20Science%20and%20Engineering%20Practices%20in%20the%20NGSS%20-%20FINAL%20060513.pdf

**Comment by deliema** [comment]
- Possible way of organizing results
  - What something is used for
  - How useful it is
  - What grade range
  - What type of lesson
  - What concepts it covers
  - What the curriculum/tool values

**Comment by deliema** [comment]
Sprint Goal: Build a comprehensive document covering existing coding resources/tools, curriculum, PD, and research for us to reference as we build our scope and sequence
